version: 2
updates:
- package-ecosystem: npm
  directory: "/test/e2e"
  schedule:
    interval: weekly
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  ignore:
  - dependency-name: d3
    versions:
    - ">= 0"
  - dependency-name: leaflet-draw
    versions:
    - ">= 0"
  - dependency-name: react-leaflet
    versions:
    - ">= 0"
  - dependency-name: redux-saga
    versions:
    - ">= 0"
