version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  ignore:
  - dependency-name: d3
    versions:
    - ">= 0"
  - dependency-name: leaflet-draw
    versions:
    - ">= 0"
