version: '3.5'
services:
  atlas: # NGINX
    build:
      context: .
    ports:
      - "8099:80"
    ipc: host
  test-lint:
    build:
      context: .
      target: build-deps
    command: npm run test-lint
  test-unit:
    build:
      context: .
      target: build-deps
    command: npm run test

  storybook:
    build:
      context: .
      target: build-deps
    command: npm run storybook
  test-e2e-visual:
    build:
      context: .
      target: build-deps
    links:
      - storybook
    command: ./scripts/visual-regression-test.sh

  test-e2e-functional:
    build:
      context: .
      target: build-deps
    command: npm run test-e2e
