version: '3.5'
services:
  atlas: # NGINX
    build:
      args:
        - NODE_ENV=acceptance
      context: .
    ipc: host

  test-unit:
    build:
      context: .
      target: build-deps
    environment:
      - NODE_ENV=development
    command: npm run test

  test-e2e:
    build:
      dockerfile: Dockerfile
      context: ./test/e2e/
    environment:
      - API_ROOT=https://api.acc.data.amsterdam.nl
      - USERNAME_EMPLOYEE
      - USERNAME_EMPLOYEE_PLUS
      - PASSWORD_EMPLOYEE
      - PASSWORD_EMPLOYEE_PLUS
    command: npm start

  # test-health-checks:
  #   image: repo.data.amsterdam.nl/datapunt/atlas-health-checks:latest
  #   environment:
  #     - API_ROOT=https://acc.api.data.amsterdam.nl
  #     - USERNAME_EMPLOYEE_PLUS
  #     - PASSWORD_EMPLOYEE_PLUS

