version: '3.5'
services:
  atlas: # NGINX
    build:
      args:
        - BUILD_ENV=acc
      context: .
    ipc: host

  atlas_aria: # NGINX
    build:
      args:
        - BUILD_ENV=acc
      context: .
    ipc: host

  test-unit-integration:
    build:
      context: .
      target: build-deps
    environment:
      - NODE_ENV=development
    command: npm run lint && npm run test

  test-e2e:
    build:
      dockerfile: Dockerfile-e2e
      context: ./test/e2e/
    links:
      - atlas:acc.data.amsterdam.nl
    environment:
      # Note that baseUrl must be formatted so
      # calls to API pass CORS check!
      - CYPRESS_baseUrl=http://acc.data.amsterdam.nl
      - USERNAME_EMPLOYEE
      - USERNAME_EMPLOYEE_PLUS
      - PASSWORD_EMPLOYEE
      - PASSWORD_EMPLOYEE_PLUS
    command: ./test-e2e.sh

  test-e2e-aria:
    build:
      dockerfile: Dockerfile-e2e-aria
      context: .
    links:
      - atlas_aria:atlas
    environment:
      - BASE_URL=http://atlas:80
      - USERNAME_EMPLOYEE
      - USERNAME_EMPLOYEE_PLUS
      - PASSWORD_EMPLOYEE
      - PASSWORD_EMPLOYEE_PLUS
    command: ./scripts/ci/test-e2e-aria.sh

  test-e2e-api-health:
    build:
      dockerfile: Dockerfile-e2e
      context: .
    links:
      - atlas:acc.data.amsterdam.nl
    environment:
      # Note that baseUrl must be formatted so
      # calls to API pass CORS check!
      - CYPRESS_baseUrl=http://acc.data.amsterdam.nl
      - USERNAME_EMPLOYEE
      - USERNAME_EMPLOYEE_PLUS
      - PASSWORD_EMPLOYEE
      - PASSWORD_EMPLOYEE_PLUS
    command: ./scripts/ci/test-e2e-api-health.sh

