version: '3.8'

services:
  data-verkenner:
    build:
      context: .
      args:
        - ENVIRONMENT=dev

    ports:
      - "3000:80"

    environment:
      - DEPLOY_ENV=production
      - TZ=Europe/Amsterdam
      - API_ROOT=https://api.data.amsterdam.nl/
      - CMS_ROOT=https://cms.data.amsterdam.nl/
      - IIIF_ROOT=https://images.data.amsterdam.nl/
      - GRAPHQL_ENDPOINT=https://api.data.amsterdam.nl/cms_search/graphql/
      - ROOT=http://localhost:3000/
      - KEYCLOAK_URL=https://iam.amsterdam.nl/auth
      - KEYCLOAK_REALM=datapunt-ad
      - KEYCLOAK_CLIENT=data-verkenner
