version: '3.5'
services:
  atlas: # NGINX
    build:
      context: .
    ipc: host

  test-unit:
    build:
      context: .
      target: build-deps
      args:
        SKIP_ENV_JSON: 1
    command: npm run test
