version: '3.5'
services:
  atlas: # NGINX
    build:
      context: .
    ports:
      - "8099:80"
    ipc: host
  unit:
    build:
      context: .
      target: build-deps
    command: npm run test-lint
