version: '3.8'

services:
  atlas:
    build:
      context: .
      args:
        - ENVIRONMENT=dev
        - DEBUG=true

    ports:
      - "3000:80"

    environment:
      - DEPLOY_ENV=production
      - TZ=Europe/Amsterdam
      - API_ROOT=https://api.data.amsterdam.nl/
      - CMS_ROOT=https://cms.data.amsterdam.nl/
      - IIIF_ROOT=https://images.data.amsterdam.nl/
      - GRAPHQL_ENDPOINT=https://api.data.amsterdam.nl/cms_search/graphql/
      - ROOT=http://localhost:3000/

  keycloak:
    image: jboss/keycloak
    command: '-b 0.0.0.0 -Djboss.http.port=8080'
    ports:
      - '8080:8080'
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
