version: 1
update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "daily"
    ignored_updates:
      - match:
          dependency_name: "d3"
      - match:
          dependency_name: "react-leaflet"
      - match:
          dependency_name: "redux-saga"
      - match:
          dependency_name: "leaflet-draw"

  - package_manager: "javascript"
    directory: "/test/e2e/package.json"
    update_schedule: "daily"

  - package_manager: "javascript"
    directory: "/test/aria/package.json"
    update_schedule: "daily"
